<?php
use think\facade\Route;
Route::miss('api/Miss/index');
Route::rule('admin/Login/index', 'admin/Login/index', 'post')->middleware(["AdminResponse"]);
Route::rule('admin/Login/logout', 'admin/Login/logout', 'get')->middleware(["AdminAuth", "AdminLog", "AdminResponse"]);
Route::rule('admin/Menu/changeStatus', 'admin/Menu/changeStatus', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Menu/add', 'admin/Menu/add', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Menu/edit', 'admin/Menu/edit', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Menu/del', 'admin/Menu/del', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/User/getUsers', 'admin/User/getUsers', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/User/changeStatus', 'admin/User/changeStatus', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/User/add', 'admin/User/add', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/User/edit', 'admin/User/edit', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/User/del', 'admin/User/del', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Auth/changeStatus', 'admin/Auth/changeStatus', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Auth/delMember', 'admin/Auth/delMember', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Auth/add', 'admin/Auth/add', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Auth/edit', 'admin/Auth/edit', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Auth/del', 'admin/Auth/del', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Auth/getGroups', 'admin/Auth/getGroups', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Auth/getRuleList', 'admin/Auth/getRuleList', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/App/changeStatus', 'admin/App/changeStatus', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/App/getAppInfo', 'admin/App/getAppInfo', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/App/add', 'admin/App/add', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/App/edit', 'admin/App/edit', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/App/del', 'admin/App/del', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceList/changeStatus', 'admin/InterfaceList/changeStatus', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceList/getHash', 'admin/InterfaceList/getHash', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceList/add', 'admin/InterfaceList/add', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceList/edit', 'admin/InterfaceList/edit', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceList/del', 'admin/InterfaceList/del', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Fields/request', 'admin/Fields/request', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Fields/response', 'admin/Fields/response', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Fields/add', 'admin/Fields/add', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Fields/upload', 'admin/Fields/upload', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Fields/edit', 'admin/Fields/edit', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Fields/del', 'admin/Fields/del', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceGroup/add', 'admin/InterfaceGroup/add', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceGroup/edit', 'admin/InterfaceGroup/edit', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceGroup/del', 'admin/InterfaceGroup/del', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceGroup/getAll', 'admin/InterfaceGroup/getAll', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceGroup/changeStatus', 'admin/InterfaceGroup/changeStatus', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/AppGroup/add', 'admin/AppGroup/add', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/AppGroup/edit', 'admin/AppGroup/edit', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/AppGroup/del', 'admin/AppGroup/del', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/AppGroup/getAll', 'admin/AppGroup/getAll', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/AppGroup/changeStatus', 'admin/AppGroup/changeStatus', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Menu/index', 'admin/Menu/index', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/User/index', 'admin/User/index', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Auth/index', 'admin/Auth/index', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/App/index', 'admin/App/index', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/AppGroup/index', 'admin/AppGroup/index', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceList/index', 'admin/InterfaceList/index', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceGroup/index', 'admin/InterfaceGroup/index', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Log/index', 'admin/Log/index', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Log/del', 'admin/Log/del', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/InterfaceList/refresh', 'admin/InterfaceList/refresh', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Index/upload', 'admin/Index/upload', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/User/own', 'admin/User/own', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/App/refreshAppSecret', 'admin/App/refreshAppSecret', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Login/getUserInfo', 'admin/Login/getUserInfo', 'get')->middleware(["AdminAuth", "AdminPermission", "AdminResponse"]);
Route::rule('admin/Auth/editRule', 'admin/Auth/editRule', 'post')->middleware(["AdminAuth", "AdminPermission", "AdminLog", "AdminResponse"]);
Route::rule('admin/Login/getAccessMenu', 'admin/Login/getAccessMenu', 'get')->middleware(["AdminAuth", "AdminResponse"]);
Route::group('admin', function() {Route::miss('admin/Miss/index');})->middleware('AdminResponse');
